---

- name: "2.1.1 Ensure autofs services are not in use"
  shell: |
     rpm -q autofs
  register: autofs_status
  failed_when: autofs_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_1
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.1

- name: "2.1.2 Ensure avahi daemon services are not in use"
  shell: |
     rpm -q avahi
  register: avahi_status
  failed_when: avahi_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_2
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.2

- name: "2.1.3 Ensure dhcp server services are not in use"
  shell: |
     rpm -q dhcp-server
  register: dhcp_server_status
  failed_when: dhcp_server_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_3
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.3

- name: "2.1.4 Ensure dns server services are not in use"
  shell: |
     rpm -q bind
  register: bind_status
  failed_when: bind_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_4
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.4

- name: "2.1.5 Ensure dnsmasq services are not in use"
  shell: |
     rpm -q dnsmasq
  register: dnsmasq_status
  failed_when: dnsmasq_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_5
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.5

- name: "2.1.6 Ensure samba file server services are not in use"
  shell: |
     rpm -q samba 
  register: samba_status
  failed_when: samba_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_6
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.6

- name: "2.1.7 Ensure ftp server services are not in use"
  shell: |
     rpm -q vsftpd 
  register: vsftpd_status
  failed_when: vsftpd_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_7
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.7

- name: "2.1.8 Ensure message access server services are not in use"
  shell: |
     rpm -q {{item}}
  with_items:
    - dovecot
    - cyrus-imapd
  register: access_server_services_status
  failed_when: access_server_services_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_8
  tags:
    - level1_server
    - s2
    - r2.1.8

- name: "2.1.9 Ensure network file system services are not in use"
  shell: |
     rpm -q nfs-utils
  register: nfs_utils_status
  failed_when: nfs_utils_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_9
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.9

- name: "2.1.10 Ensure nis server services are not in use"
  shell: |
     rpm -q ypserv
  register: ypserv_status
  failed_when: ypserv_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_10
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.10

- name: "2.1.11 Ensure print server services are not in use"
  shell: |
     rpm -q cups
  register: cups_status
  failed_when: cups_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_11
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.11

- name: "2.1.12 Ensure rpcbind services are not in use"
  shell: |
     rpm -q rpcbind
  register: rpcbind_status
  failed_when: rpcbind_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_12
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.12

- name: "2.1.13 Ensure rsync services are not in use"
  shell: |
     rpm -q rsync-daemon
  register: rsync_daemon_status
  failed_when: rsync_daemon_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_13
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.13

- name: "2.1.14 Ensure snmp services are not in use"
  shell: |
     rpm -q net-snmp
  register: net_snmp_status
  failed_when: net_snmp_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_14
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.14

- name: "2.1.15 Ensure telnet server services are not in use"
  shell: |
     rpm -q telnet-server
  register: telnet_server_status
  failed_when: telnet_server_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_15
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.15

- name: "2.1.16 Ensure tftp server services are not in use"
  shell: |
     rpm -q tftp-server
  register: tftp_server_status
  failed_when: tftp_server_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_16
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.16

- name: "2.1.17 Ensure web proxy server services are not in use"
  shell: |
     rpm -q squid
  register: squid_status
  failed_when: squid_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_17
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.17

- name: "2.1.18 Ensure web server services are not in use"
  shell: |
     rpm -q {{item}}
  with_items:
    - httpd
    - nginx
  register: web_server_services_status
  failed_when: web_server_services_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_18
  tags:
    - level1_server
    - s2
    - r2.1.18

- name: "2.1.19 Ensure xinetd services are not in use"
  shell: |
     rpm -q xinetd
  register: xinetd_status
  failed_when: xinetd_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_19
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.19

- name: "2.1.20 Ensure X window server services are not in use"
  shell: |
     rpm -q xorg-x11-server-common
  register: xorg_x11_server_common_status
  failed_when: xorg_x11_server_common_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_1_20
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.1.20

- name: "2.1.21 Ensure mail transfer agent is configured for local-only mode"
  shell: |
    ss -lntu | grep -E ':25\s' | grep -E -v '\s(127.0.0.1|::1):25\s'
  changed_when: no
  register: mail_local_mode
  failed_when: mail_local_mode.stdout|length > 1
  ignore_errors: yes
  when:
    - rule_2_1_21
  tags:
    - level1_server
    - level1_workstation
    - s2
    - r2.1.21

- name: "2.2.1 Ensure ftp client is not installed"
  shell: |
    rpm -q ftp
  register: ftp_status
  failed_when: ftp_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_2_1
  tags:
    - level1_server
    - level1_workstation
    - s2
    - r2.2.1

- name: "2.2.2 Ensure ldap client is not installed"
  shell: |
    rpm -q openldap-clients
  register: openldap_status
  failed_when: openldap_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_2_2
  tags:
    - level1_server
    - level1_workstation
    - s2
    - r2.2.2

- name: "2.2.3 Ensure nis client is not installed"
  shell: |
    rpm -q ypbind
  register: ypbind_status
  failed_when: ypbind_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_2_3
  tags:
    - level1_server
    - level1_workstation
    - s2
    - r2.2.3
    
- name: "2.2.4 Ensure telnet client is not installed"
  shell: |
    rpm -q telnet
  register: telnet_status
  failed_when: telnet_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_2_4
  tags:
    - level1_server
    - level1_workstation
    - s2
    - r2.2.4    
    
- name: "2.2.5 Ensure tftp client is not installed"
  shell: |
    rpm -q tftp
  register: tftp_status
  failed_when: tftp_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_2_5
  tags:
    - level1_server
    - level1_workstation
    - s2
    - r2.2.5
    

- name: "2.3.1 Ensure time synchronization is in use"
  shell: |
    rpm -q chrony
  changed_when: no
  register: timesync_daemon_status
  failed_when: '"chrony-" not in  timesync_daemon_status.stdout'
  ignore_errors: yes
  when:
    - rule_2_3_1
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.3.1



- name: "2.3.2 Ensure chrony is configured| server"
  shell: |
    grep -Prs -- '^\h*(server|pool)\h+[^#\n\r]+' /etc/chrony.conf /etc/chrony.d/
  register: chrony_server
  failed_when: chrony_server.stdout|length < 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_3_2
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.3.2
    - chrony

- name: "2.3.3 Ensure chrony is configured | options"
  shell: |
    grep -Psi -- '^\h*OPTIONS=\"?\h*([^#\n\r]+\h+)?-u\h+root\b' /etc/sysconfig/chronyd
  register: chrony_options
  failed_when: chrony_options.stdout|length > 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_3_3
  tags:
    - level1_workstation
    - level1_server
    - s2
    - r2.3.3
    - chrony

- name: "2.4.1.1 Ensure cron daemon is enabled and active"
  block:
    - name: "2.4.1.1 Ensure cron daemon is enabled and running | enabled"
      shell: systemctl is-enabled crond
      register: crond_status
      failed_when: '"enabled" not in crond_status.stdout'
      changed_when: no
    - name: "2.4.1.1 Ensure cron daemon is enabled and running | active"
      shell:  |
        systemctl status crond | grep 'Active: active (running)'
      register: crond_status_run
      failed_when: '"active" not in crond_status_run.stdout'
      changed_when: no
  ignore_errors: yes
  when:
    - rule_2_4_1_1
  tags:
    - level1_server
    - level1_workstation
    - r2.4.1.1
    - s2
    
- name: "2.4.1.2 | Ensure permissions on /etc/crontab are configured "
  shell: stat -Lc "%n %#a %U %G" /etc/crontab
  register: crontab_permission_status
  failed_when: '"root root" not in crontab_permission_status.stdout or not crontab_permission_status.stdout | regex_search("[0246]00")'
  ignore_errors: yes
  when:
    - rule_2_4_1_2
  tags:
    - level1_server
    - level1_workstation
    - r2.4.1.2
    - s2

- name: "2.4.1.3 | Ensure permissions on /etc/cron.hourly are configured "
  shell: stat -Lc "%n %#a %U %G" /etc/cron.hourly
  register: cron_hourly_permission_status
  failed_when: '"root root" not in cron_hourly_permission_status.stdout or not cron_hourly_permission_status.stdout | regex_search("[02467]00")'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_4_1_3
  tags:
    - level1_server
    - level1_workstation
    - r2.4.1.3
    - s2

- name: "2.4.1.4 | Ensure permissions on /etc/cron.daily are configured "
  shell: stat -Lc "%n %#a %U %G" /etc/cron.daily
  register: cron_daily_permission_status
  failed_when: '"root root" not in cron_daily_permission_status.stdout or not cron_daily_permission_status.stdout | regex_search("[02467]00")'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_4_1_4
  tags:
    - level1_server
    - level1_workstation
    - r2.4.1.4
    - s2

- name: "2.4.1.5 | Ensure permissions on /etc/cron.weekly are configured "
  shell:  stat -Lc "%n %#a %U %G" /etc/cron.weekly
  register: cron_weekly_permission_status
  failed_when: '"root root" not in cron_weekly_permission_status.stdout or not cron_weekly_permission_status.stdout | regex_search("[02467]00")'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_4_1_5
  tags:
    - level1_server
    - level1_workstation
    - r2.4.1.5
    - s2

- name: "2.4.1.6 | Ensure permissions on /etc/cron.monthly are configured "
  shell:  stat -Lc "%n %#a %U %G" /etc/cron.monthly
  register: cron_monthly_permission_status
  failed_when: '"root root" not in cron_monthly_permission_status.stdout or not cron_monthly_permission_status.stdout | regex_search("[02467]00")'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_4_1_6
  tags:
    - level1_server
    - level1_workstation
    - r2.4.1.6
    - s2

- name: "2.4.1.7 | Ensure permissions on /etc/cron.d are configured "
  shell:  stat -Lc "%n %#a %U %G" /etc/cron.d
  register: crond_permission_status
  failed_when: '"root root" not in crond_permission_status.stdout or not crond_permission_status.stdout | regex_search("[02467]00")'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_2_4_1_7
  tags:
    - level1_server
    - level1_workstation
    - r2.4.1.7
    - s2
    
- name: "2.4.1.8 | Ensure cron is restricted to authorized users "
  block:
    - name: "2.4.1.8 | Check if cron.deny exists "
      shell:  stat -Lc "%n %#a %u/%U %g/%G" /etc/cron.deny
      register: stat_cron_deny
      failed_when:  'stat_cron_deny.stdout is not search("06[04]0") or stat_cron_deny.rc != 0'
      changed_when: no

    - name: "2.4.1.8 | Check if cron.allow exists "
      shell:  stat -Lc "%n %#a %u/%U %g/%G" /etc/cron.allow
      register: stat_cron_allow
      failed_when:  stat_cron_allow.stdout is not search("06[04]0") or stat_cron_allow.rc != 0
      changed_when: no
  ignore_errors: yes
  when:
    - rule_2_4_1_8
  tags:
    - level1_server
    - level1_workstation
    - r2.4.1.8
    - s2
    
- name: "2.4.2.1 | Ensure at is restricted to authorized users "
  block:
    - name: "2.4.2.1 | Check if at.deny"
      shell:  stat -Lc "%n %#a %u/%U %g/%G" /etc/at.deny
      register: stat_at_deny
      failed_when:  stat_at_deny.stdout is not search("06[04]0")
      changed_when: no

    - name: "2.4.2.1 | Check if at.allow exists "
      shell:  stat -Lc "%n %#a %u/%U %g/%G" /etc/at.allow
      register: stat_at_allow
      failed_when:  stat_at_allow.stdout is not search("06[04]0")
      changed_when: no
  ignore_errors: yes
  when:
    - rule_2_4_2_1
  tags:
    - level1_server
    - level1_workstation
    - r2.4.2.1
    - s2
