---
- name: "3.1.1 Ensure IPv6 status is identified"
  script: 
    cmd: rule_3_1_1.sh
  register: script_return
  failed_when: 'not ipv6_active and "enabled" in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_1_1
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.1.1
    
- name: "3.1.2 Ensure wireless interfaces are disabled"
  script: 
    cmd: rule_3_1_2.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_1_2
  tags:
    - level1_server
    - level2_workstation
    - s3
    - r3.1.2
    
- name: "3.1.3 Ensure bluetooth services are not in use"
  shell: |
     rpm -q bluez
  register: bluez_status
  failed_when: bluez_status.rc != 1
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_1_3
  tags:
    - level1_workstation
    - level1_server
    - s3
    - r3.1.3
 
    
- name: "3.2.1 Ensure dccp kernel module is not available"
  script:
    cmd: rule_3_2_1.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_2_1
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.2.1
    
- name: "3.2.2 Ensure tipc kernel module is not available"
  script:
    cmd: rule_3_2_2.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_2_2
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.2.2

- name: "3.2.3 Ensure rds kernel module is not available"
  script:
    cmd: rule_3_2_3.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_2_3
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.2.3

- name: "3.2.4 Ensure sctp kernel module is not available"
  script:
    cmd: rule_3_2_4.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_2_4
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.2.4
    
- name: "3.3.1 Ensure ip forwarding is disabled"
  script:
    cmd: rule_3_3_1.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_1
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.1
    
- name: "3.3.2 Ensure packet redirect sending is disabled"
  script:
    cmd: rule_3_3_2.sh 
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_2
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.2
    
- name: "3.3.3 Ensure bogus icmp responses are ignored"
  script:
    cmd: rule_3_3_3.sh 
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_3
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.3  
    
- name: "3.3.4 Ensure broadcast icmp requests are ignored"
  script:
    cmd: rule_3_3_4.sh 
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_4
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.4
    
- name: "3.3.5 Ensure icmp redirects are not accepted"
  script:
    cmd: rule_3_3_5.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_5
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.5
    
- name: "3.3.6 Ensure secure icmp redirects are not accepted"
  script:
    cmd: rule_3_3_6.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_6
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.6
    
- name: "3.3.7 Ensure reverse path Filtering is enabled"
  script:
    cmd: rule_3_3_7.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_7
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.7
    
- name: "3.3.8 Ensure source routed packets are not accepted"
  script:
    cmd: rule_3_3_8.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_8
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.8
    
- name: "3.3.9 Ensure suspicious packets are logged"
  script:
    cmd: rule_3_3_9.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_9
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.9
        
- name: "3.3.9 Ensure IPv6 router advertisements are not accepted"
  script:
    cmd: rule_3_3_9.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_9
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.9

- name: "3.3.10 Ensure tcp syn cookies is enabled"
  script:
    cmd: rule_3_3_10.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_10
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.10

- name: "3.3.11 Ensure ipv6 router advertisements are not accepted"
  script:
    cmd: rule_3_3_11.sh
  register: script_return
  failed_when: '"PASS" not in script_return.stdout'
  changed_when: no
  ignore_errors: yes
  when:
    - rule_3_3_11
  tags:
    - level1_server
    - level1_workstation
    - s3
    - r3.3.11



